version: '3.4'

services:
  database:
    container_name: platform-backend-database
    networks:
      - platform-backend
    image: postgres:11.1-alpine
    restart: always
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./.data/db:/var/lib/postgresql/data

  server:
    networks:
      - platform-backend
    container_name: platform-backend
    build:
      context: .
      dockerfile: Dockerfile
      args:
        port: ${PLATFORM_BACKEND_PORT}
    ports:
      - ${PLATFORM_BACKEND_PORT}:${PLATFORM_BACKEND_PORT}
    depends_on:
      - database
    volumes:
      - ./migrations:/root/migrations
      - ./config.json:/root/config.json

networks:
  platform-backend:
