version: '3.4'

services:
  database:
    image: postgres:11.1-alpine
    restart: always
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./.data/db:/var/lib/postgresql/data

  server:
    image: go-clean-architecture
    container_name: "go-clean-architecture"
    build: ./
    command: ./app
    ports:
      - 8000:8000
    depends_on:
      - database